import { useLocation } from 'wouter';

export default function TermsOfUse() {
  const [, navigate] = useLocation();
  return (
    <div className="min-h-screen w-full bg-background">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <button
          onClick={() => navigate('/')}
          className="text-sm text-primary hover:underline mb-8"
        >
          ← Back to Doyang
        </button>

        <h1 className="text-3xl font-extrabold tracking-tight text-foreground mb-2">
          Terms of Use
        </h1>
        <p className="text-sm text-muted-foreground mb-10">
          Effective date: July 12, 2026
        </p>

        <div className="space-y-8 text-foreground/90 leading-relaxed">
          <section>
            <p>
              These Terms of Use ("Terms") govern your access to and use of Doyang,
              a creditworthiness and marketplace platform operated from Siaya, Kenya.
              By creating an account or using Doyang, you agree to these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">1. Eligibility</h2>
            <p className="text-muted-foreground">
              You must be at least 18 years old and capable of entering into a
              binding contract under Kenyan law to use Doyang.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">2. Account Roles</h2>
            <p className="text-muted-foreground">
              Doyang offers three roles: Retailer, Wholesaler, and Buyer. You select
              a role at sign-up and are responsible for the accuracy of the
              information you provide, including your business details and uploaded
              M-Pesa statements.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">3. Credit Reports and Loan Offers</h2>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Credit scores, grades, and recommended limits generated by Doyang are automated estimates based on the statements you upload. They are not a guarantee of creditworthiness or repayment ability, and Doyang makes no warranty as to their accuracy.</li>
              <li>Loan offers are agreements directly between a wholesaler and a retailer. Doyang facilitates the offer, acceptance, and repayment collection process, but is not a party to the underlying credit agreement and does not guarantee repayment to wholesalers.</li>
              <li>Retailers are responsible for repaying accepted loan offers according to the agreed schedule. Failure to pay may result in a loan being marked as defaulted.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">4. Marketplace and Hire Purchase</h2>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Sellers are responsible for the accuracy of their product listings, stock levels, and fulfillment of orders.</li>
              <li>Buyers agree to pay the full purchase price, or in the case of Hire Purchase, the deposit and all scheduled instalments, on time.</li>
              <li>Doyang is not responsible for the quality, safety, or legality of items listed by sellers, or for disputes between buyers and sellers, though we may assist in good faith where possible.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">5. Payments</h2>
            <p className="text-muted-foreground">
              All payments are processed through Paystack, including M-Pesa STK
              push, card charges, and bank transfers. By using Doyang's payment
              features, you also agree to Paystack's applicable terms. Doyang
              charges a platform fee (typically 5–10%) on transactions settled to
              sellers and wholesalers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">6. Prohibited Conduct</h2>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Uploading fraudulent or altered M-Pesa statements</li>
              <li>Providing false business or identity information</li>
              <li>Listing counterfeit, stolen, or illegal goods</li>
              <li>Attempting to circumvent Doyang's payment or fee systems</li>
              <li>Using the platform for money laundering or any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">7. Account Suspension</h2>
            <p className="text-muted-foreground">
              We may suspend or terminate accounts that violate these Terms, engage
              in fraudulent activity, or pose a risk to other users of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">8. Limitation of Liability</h2>
            <p className="text-muted-foreground">
              Doyang is provided "as is." To the fullest extent permitted by Kenyan
              law, we are not liable for indirect, incidental, or consequential
              damages arising from your use of the platform, including losses
              related to loan defaults, marketplace disputes, or payment failures
              caused by third-party providers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">9. Governing Law</h2>
            <p className="text-muted-foreground">
              These Terms are governed by the laws of the Republic of Kenya. Any
              disputes shall be subject to the exclusive jurisdiction of the courts
              of Kenya.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">10. Changes to These Terms</h2>
            <p className="text-muted-foreground">
              We may update these Terms from time to time. Continued use of Doyang
              after changes take effect constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">11. Contact Us</h2>
            <p className="text-muted-foreground">
              Doyang<br />
              Siaya, Kenya<br />
              Email: <a href="mailto:jamesodero40@gmail.com" className="text-primary hover:underline">jamesodero40@gmail.com</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
